version: 2
before:
  hooks:
    - go mod tidy -v
builds:
  - id: linux_arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/wwqgtxx/nezha/service/singleton.Version={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
  - id: linux_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/wwqgtxx/nezha/service/singleton.Version={{.Version}}
    flags:
      - -trimpath
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
  - id: windows_amd64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/wwqgtxx/nezha/service/singleton.Version={{.Version}}
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
  - id: windows_arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/wwqgtxx/nezha/service/singleton.Version={{.Version}}
    flags:
      - -trimpath
    goos:
      - windows
    goarch:
      - arm64
    main: ./cmd/dashboard
    binary: dashboard-{{ .Os }}-{{ .Arch }}
snapshot:
  version_template: "dashboard"
